name: golang

on:
  workflow_dispatch:
  pull_request:
defaults:
  run:
    working-directory: go

jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: actions/setup-go@main
        with:
          go-version: 1.18
      - run: make generate
        name: Generate test mocks
      - run: make unit-test
        name: run unit test

  intergration-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: go
    steps:
      - uses: actions/checkout@main
      - uses: actions/setup-go@main
        with:
          go-version: 1.18
      - run: make integration-test
