name: golang

on:
  workflow_dispatch:
  pull_request:

jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: 1.19
      - run: make generate
        name: Generate test mocks
      - run: make unit-test
        name: run unit test

